location = /links {
    root /opt/links;
    try_files /links.html =404;
}

location = /Welcome! {
    root /opt/links;
    try_files /26765572@2x.png =404;
}

location = /Suroi {
    root /opt/links;
    try_files /suroi.svg =404;
}

location = /Survev {
    root /opt/links;
    try_files /survev_logo_full.png =404;
}

location = /Survev.de {
    root /opt/links;
    try_files /survev-de_logo_full.png =404;
}

location = /Resurviv.biz {
    root /opt/links;
    try_files /resurviv_logo_full.png =404;
}

location = /Rezurvev.ru {
    root /opt/links;
    try_files /rezurvev_logo_full.png =404;
}

location = /Surviv.io {
    root /opt/links;
    try_files /surviv_logo_full.png =404;
}

location = /Image_1776869044725_732.jpg {
    root /opt/links;
    try_files /Image_1776869044725_732.jpg =404;
}
